version: '3.8'

services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    # volumes:
    #   - .:/django-wildwish
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:

    
# services:
#   db:
#     image: postgres:12
#     # Add volume to persist data beyond life of the container
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#         # These need to be changed to match db
#       - POSTGRES_DB=wwpsql_dev
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#   web:
#     build: .
#     # Need to also cd into /frontend and run 'npm run dev'
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/django-wildwish
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

# volumes:
#   postgres_data: